microservice
go-park-mail-ru/2021_2_GORYACHIE_MEKSIKANSI pull request #33
Opened 2021-11-26 22:35 UTC by Captain-Matroskin

Добавлены 3 микросервиса (Корзина, Авторизация, Рестораны)
Добавлено базовое заполнение ресторанов

2021-11-27 18:31 UTC, ChocolaterToba commented
Переведите названи файлов/пакетов/директорий в lowercase везде, а то сейчас как попало

2021-11-27 18:57 UTC, ChocolaterToba requested changes

2021-11-27 18:57 UTC, ChocolaterToba commented on build/SetUp.go
>  }
У меня есть подозрение, что лучше всё-таки выделить тип под result
Ну или отдельно возвращать эти врапперы

2021-11-27 23:15 UTC, Captain-Matroskin commented on build/SetUp.go
>  }
Отдельно, думаю, не эффективно, так как их кол-во может увеличиться
Поэтому сделаю структурой

2021-11-29 18:45 UTC, ChocolaterToba commented
На вид норм

2021-11-29 18:45 UTC, ChocolaterToba approved these changes

2021-11-29 18:48 UTC, merged