Metrics
go-park-mail-ru/2021_2_GORYACHIE_MEKSIKANSI pull request #37
Opened 2021-12-18 12:45 UTC by Captain-Matroskin

Добавлены метрики + фиксы в докере

2021-12-18 20:46 UTC, ChocolaterToba requested changes

2021-12-18 20:46 UTC, ChocolaterToba commented on internals/middleware/api/api.go
> +		}
Мне кажется, ошибка в middleware метрик не должна  влиять на работу основного сервака, т.е. тут следует вернуть клиенту то, что хотел вернуть сервер

2021-12-18 20:46 UTC, ChocolaterToba commented on internals/middleware/api/api.go
> +		timeStart, errConvertTime := util.InterfaceConvertTime(timeStartCtx)
Почему бы просто перед вызовом хендера не сделать timeStart := time.Now()?

2021-12-18 20:46 UTC, ChocolaterToba commented on internals/middleware/orm/gomock_reflect_281378583/prog.go
> +
Ненужная  пустая строчка

2021-12-18 21:02 UTC, Captain-Matroskin commented on internals/middleware/api/api.go
> +		timeStart, errConvertTime := util.InterfaceConvertTime(timeStartCtx)
> Почему бы просто перед вызовом хендера не сделать timeStart := time.Now()?

Не совсем понял
То есть после 257 строчки там сделать timeStart := time.Now()?
А уже, например, в 268 строчки  или ниже получать timeEnd := time.Now()?

2021-12-18 21:50 UTC, Captain-Matroskin commented on internals/middleware/orm/gomock_reflect_281378583/prog.go
> +
но ведь это сгенерированный файлик, не мой...

2021-12-18 21:54 UTC, Captain-Matroskin commented on internals/middleware/api/api.go
> +		}
Да, но тогда в случае ошибки как прервать дальнейшее выполнение? break?

и насчет другого кода: как я понимаю, h(ctx) выше над кодом, поэтому этот куско выполняется после основного хендлера. То есть он не прервет работу хенделра, так как он уже отработал

2021-12-20 14:28 UTC, ChocolaterToba commented on internals/middleware/api/api.go
> +		timeStart, errConvertTime := util.InterfaceConvertTime(timeStartCtx)
Именно
Тут ни к чему контекст запроса использовать, он же в той же оперативке храниться будет

2021-12-20 14:30 UTC, ChocolaterToba commented on internals/middleware/api/api.go
> +		}
Так я не про работу хендлера
Я про то, что странно, что если errConvert не nil (как я понимаю, это означает, что в метриках случилась ошибка), то пользователю отдатся 500, хотя его запрос сам выполнился успешно

2021-12-20 15:49 UTC, Captain-Matroskin commented on internals/middleware/api/api.go
> +		}
В целом да, понял, согласен
Но в этом коде (выделенные выше) как раз-таки случай, когда reqId (реквест ид пользователя) не был сгенерирован. Эта проверка идет в других хенделрах. То есть в данном случае всё равно в другом месте будет internalServer (500)

2021-12-20 19:03 UTC, ChocolaterToba commented on internals/middleware/api/api.go
> +		}
Так и зачем переопределять этот статус тогда?

2021-12-20 19:04 UTC, ChocolaterToba approved these changes

2021-12-20 19:07 UTC, merged